### ISSUE TITLE
nodejs8能否支持？

### ISSUE THREAD

**Issue by Bluebang** [k8w/tsrpc#11]

**Comment by k8w** [comment]
开发环境必须在 Node@12 +
但 `npm run build` 后的版本，是可以运行在 Node@10 上的。
Node@8 没有测试，理论上可以，您可以试试看，有问题随时反馈~

**Comment by Bluebang** [comment]
我想部署在淘宝云函数平台上，那边的node是8.9.0。编译后有包要求运行在>=10的node环境。请问这个有办法解决么

**Comment by Bluebang** [comment]
我想部署在淘宝云函数平台上，那边的node是8.9.0。编译后有包要求运行在>=10的node环境。请问这个有办法解决么

**Comment by Bluebang** [comment]
`yarn install v1.22.11 [1/4] Resolving packages... [2/4] Fetching packages... error chalk@4.1.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "9.9.0" error Found incompatible module. info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by k8w** [comment]
目前 TSRPC 中依赖了 NPM 包 `chalk`，该依赖需要 Node 版本大于 10，暂时无法支持 Node 8.
