### ISSUE TITLE
tsbuffer.TSBuffer is not a constructor

### ISSUE THREAD

**Issue by poerlang** [k8w/tsrpc#12]
创建项目后，运行客户端，显示：

tsbuffer.TSBuffer is not a constructor

![image](https://user-images.githubusercontent.com/3243514/147799179-3677458e-2c01-41d9-b1da-8ae7456443e6.png)
[test.zip](https://github.com/k8w/tsrpc/files/7795150/test.zip)

不太清楚具体原因，可否抽空帮忙看看

**Comment by k8w** [comment]
感谢反馈，似乎是由于 `react-scripts` 版本更新了所致，我先看一下。

**Comment by k8w** [comment]
经确认，改问题来自于 `react-scripts` 新版本的 Bug：
https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined

新版本对 `cjs` 支持不友好，最新版本的 tsrpc-browser 已经修复此问题。

**解决办法**
在 `frontend` 下执行：

```
npm i tsrpc-browser@latest
```

更新到 `tsrpc-browser` 3.1.5 以上版本

**Comment by k8w** [comment]
或者重新 `npx create-tsrpc-app@latest` 也可
