### ISSUE TITLE
使用any类型发送,服务端的req里没有该字段

### ISSUE THREAD

**Issue by fengssy** [k8w/tsrpc#13]
tsrpc:3.1.9
服务端的代码和日志截图:
![image](https://user-images.githubusercontent.com/5457617/153115360-8047b766-4a0c-444e-bdc3-ec6a3811b7d5.png)
![image](https://user-images.githubusercontent.com/5457617/153115464-b3cd2975-de8b-4c8b-b0ec-93a6aec04cf2.png)
![image](https://user-images.githubusercontent.com/5457617/153115598-a8448701-a79e-494f-8771-8d40669a73cc.png)

客户端发送的日志截图:
![image](https://user-images.githubusercontent.com/5457617/153115686-cc666a61-ec87-4b89-934f-7496c68a49ce.png)

补充一个,serviceProto.ts确实有生成这字段:
![image](https://user-images.githubusercontent.com/5457617/153115950-cbe5020c-9d51-47db-87fb-d1f02fc29048.png)

求解

**Comment by k8w** [comment]
可否提供一个最小可重现的 demo 呀？

或可以尝试一下几种方式：
1. 确认 `serviceProto.ts` 是否在前后端一致？
2. 升级前后端的 tsrpc 及 tsrpc-browser 到最新版本

**Comment by fengssy** [comment]
[testAny.zip](https://github.com/k8w/tsrpc/files/8029928/testAny.zip)
两个app分别npm install后,能重现

**Comment by fengssy** [comment]
我找到问题了
是客户端的serviceProto.ts没有同步
我是配置成copy方式同步

但我觉得按正常操作, 两边都启动了,应该会执行同步, 除非说文件比较方面有什么逻辑漏洞导致, 这文件在某个时候被同步规则检测遗漏

**Comment by k8w** [comment]
> 但我觉得按正常操作, 两边都启动了,应该会执行同步, 除非说文件比较方面有什么逻辑漏洞导致, 这文件在某个时候被同步规则检测遗漏

@fengssy 确实如此，`npm run dev` 期间，文件变化会自动同步，但不在 `npm run dev` 期间的文件变化，就不会同步了。
是否有在 `npm run dev` 之外，单独进行过 `npm run proto` 的操作呀？

**Comment by fengssy** [comment]
> 
我能重现问题现象了:
启动前服务端改了协议字段, 再执行 `tsrpc-cli dev` 这时候serviceProto.ts生成新的了,但没执行同步操作, 导致客户端文件是旧的
![image](https://user-images.githubusercontent.com/5457617/153140474-25f10c6f-d937-4ac9-8f47-87b78a96adde.png)

所以建议启动时,在生成后,也执行/检测一下同步

**Comment by k8w** [comment]
收到，我看一下，下个小版本优化。
