### ISSUE TITLE
文档有误:服务端->实时消息服务->监听单个消息,call: MsgChat 类型应为MsgCall<MsgChat>

### ISSUE THREAD

**Issue by fengssy** [k8w/tsrpc#14]
https://tsrpc.cn/docs/server/msg-service.html#%E7%9B%91%E5%90%AC%E5%8D%95%E4%B8%AA%E6%B6%88%E6%81%AF
不知道我有没有理解错 ^_^

**Comment by k8w** [comment]
你理解的对，文档有误，我修改一下~
感谢~~~~

**Comment by k8w** [comment]
已修复
