### ISSUE TITLE
协议接口增加新属性兼容问题

### ISSUE THREAD

**Issue by harochen75** [k8w/tsrpc#17]
原先协议接口属性：
export interface ReqLogin{
    username: string
}

后因为需求变更，需要增加字段：客户端类型
export interface ReqLogin{
    username: string,
    clientType:number
}

旧客户端未更新协议之前，访问新的服务器，会提示fail:Missing required property `clientType`
怎么做到兼容的处理呢？

**Comment by k8w** [comment]
新字段设为可选 `clientType?: number`
或者蓝绿发布到不同 URL

**Comment by harochen75** [comment]
嗯，找到文档说明。 
文档地址：https://tsrpc.cn/docs/server/deployment/proto-change.html
