### ISSUE TITLE
tsrpc.config.ts 配置, 接口创建异常.

### ISSUE THREAD

**Issue by Dssssds** [k8w/tsrpc#21]
# 问题描述
1.  tsrpc.config.ts配置多个[proto].
2. 在 「protocolsA」下新建一个PtlTest.ts 协议
3. 在「src/api/A」成功创建了API
4. **[异常]** **在「src/api/」 下 增加了一个「protocolsA」 的API文件**

<img width="1756" alt="image" src="https://user-images.githubusercontent.com/17268259/164728082-2b05ecb0-6c35-492c-a9e9-39ee93524e9c.png">

**Comment by k8w** [comment]
tsrpc-cli@2.4.3 已经修复
