### ISSUE TITLE
about version.

### ISSUE THREAD

**Issue by gbcmikeblue** [k8w/tsrpc#26]
Why the latest tag is v2.3.2?Why the Official website  latest version is v3.2.3? And we need releases version.

**Comment by k8w** [comment]
![image](https://user-images.githubusercontent.com/1681689/171147121-29ad4101-f035-4970-b3ce-fb83b1a73802.png)

I don't find `v2.3.2`, where you see it ?

**Comment by gbcmikeblue** [comment]
> ![image](https://user-images.githubusercontent.com/1681689/171147121-29ad4101-f035-4970-b3ce-fb83b1a73802.png)
> 
> I don't find `v2.3.2`, where you see it ?


> oh sorry, now I find it in `https://www.npmjs.com/package/tsrpc`.  👍 
> You should be update the version in the `[github.com](https://github.com/k8w/tsrpc/releases)`. thanks .
