### ISSUE TITLE
联机游戏的后端如何使用cocos的物理引擎

### ISSUE THREAD

**Issue by liujin1993** [k8w/tsrpc#35]
如题想请教下，用cocos写单机游戏的时候可以使用其自带的物理引擎，各个物体的位置都是由物理引擎计算的，而联机游戏需要前后端共用一套逻辑，这时后端如何使用cocos的物理引擎呢

**Comment by k8w** [comment]
好问题，一般来说有几种方式。

1. 采用主机模式，主机跑在浏览器里，就可以完整运行 Cocos 游戏逻辑。（变种方法是尝试 Pupeteer 这样的 Headless 浏览器，让浏览器以无渲染模式跑在 Server） 
2. 不使用 Cocos 的物理引擎，而是将完整的游戏逻辑，单另实现。

**Comment by liujin1993** [comment]
学到了！3q！
