### ISSUE TITLE
cocos creator 3.7.2无法使用

### ISSUE THREAD

**Issue by chenquanjun** [k8w/tsrpc#44]
使用import { WsClient } from 'tsrpc-browser';
编辑器提示Error: Error: Unexpected export statement in CJS module.

**Comment by chenquanjun** [comment]
我用了官方提供的这个方案暂时解决了
https://forum.cocos.org/t/topic/119511/72

**Comment by k8w** [comment]
感谢反馈，`tsrpc-browser@3.4.13` `tsrpc-miniapp@3.4.13` 已修复此问题。
