### ISSUE TITLE
支持 TypeORM

### ISSUE THREAD

**Issue by minjs1cn** [k8w/tsrpc#56]
## 背景

使用TypeORM来操作Mysql数据库，使用装饰器来定义Entity

```
/**
 * 用户
 */
@Entity('sys_user')
export class UserEntity extends BaseEntity {
  @ManyToOne(() => DepartmentEntity, (department) => department)
  @JoinColumn()
  department: DepartmentEntity;

  @ManyToMany(() => RoleEntity)
  @JoinTable()
  roles: RoleEntity[];

  @Column({ comment: '邮箱' })
  email: string;

  @Column({ comment: '密码' })
  password: string;

  @Column({ comment: '昵称' })
  nickname: string;

  @Column({
    comment: '状态 0-禁用 1-启用',
    type: 'enum',
    enum: UserStatus,
    default: UserStatus.Enabled,
  })
  status: UserStatus;
}
```

将Entit作为类型使用

```
export type ResGetData= UserEntity;
```
启动报错，信息如下：

⨯ Cannot find reference target '../entities/sys/user.entity/UserEntity'
    at ResGetData
    at PtlGetData
⨯ ServiceProto 生成失败，请检查 TypeScript 代码是否编译报错: src/shared/protocols/serviceProto.ts

看起来装饰器的Entity在当前环境无法正确编译

**Comment by minjs1cn** [comment]
已解决部分问题

1. protocols放弃引用entity的定义
2. tsconfig增加配置
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "emitDecoratorMetadata": true
  }
}
```
可以正常运行，但是如何去复用entity定义的类型呢

**Comment by minjs1cn** [comment]
> 已解决部分问题
> 
> 1. protocols放弃引用entity的定义
> 2. tsconfig增加配置
> 
> ```
> {
>   "compilerOptions": {
>     "experimentalDecorators": true,
>     "strictPropertyInitialization": false,
>     "emitDecoratorMetadata": true
>   }
> }
> ```
> 
> 可以正常运行，但是如何去复用entity定义的类型呢

**Comment by k8w** [comment]
是的，目前还没有支持 class 类型，支持 TypeORM 在 Todo List 中...

当然，如果使用 MongoDB 的话，可以无需 ORM...
